disabled = false
languageCode = "zh-tw"  #文字编码
languageName = "繁體中文"  #多语言显示名称
weight = 3
title = "SM.DOCTOR"

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo1.png" #夜晚模式LOGO
  # secondaryLogo = "logo2.png" #白天模式LOGO
  description = "人類健康計劃 — 健康哲學、健康的第一性原理、健康系統工程方法論、醫養一體化方法、大健康產業生態構建。"

[params.author]
  image = "/img/logo3.png" #首页中心LOGO
  name = "Systemic Medicine Doctor" #首页中间LOGO下名称
  headline = "『人類健康計劃』大健康文化全球化推廣方案"   #首页标语
  bio = "SMD循證醫學理論與應用"   #文章页作者图标下说明标语
  links = [
    { x-twitter = "https://x.com/BlueyASI_org" },
    { bluesky = "#" },
    { facebook = "#" },
    { instagram = "#" },
    { telegram = "#" },
    { github = "mailto:ohulab.org@gmail.com" },
  ]  #文章页作者LOGO下社交媒体图标连接
  email = "ohulab.org@gmail.com"
