disabled = false
languageCode = "zh-cn"  #文字编码
languageName = "简体中文"  #多语言显示名称
weight = 2
title = "SM.DOCTOR"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo1.png" #夜晚模式首页左上角LOGO
  # secondaryLogo = "logo2.png" #白天模式首页左上角LOGO
  description = "人类健康计划 — 健康哲学、健康的第一性原理、健康系统工程方法论、医养一体化方法、大健康产业生态构建。"

[params.author]
  image = "/img/logo3.png" #首页中心LOGO
  name = "Systemic Medicine Doctor" #首页中间LOGO下大字名称
  headline = "为全球加盟医馆赋能的专业人工智能"   #首页标语
  bio = "SMD循证医学理论与应用"   #文章页作者图标下说明标语
  links = [
    { weixin = "../../Contact" },
    { toutiao = "https://www.toutiao.com/c/user/token/MS4wLjABAAAAg0e3TfgJwAzj2dS6wu8Mg3dWTIzAjTGU26mQGm4AKjQ/" },
    { redbook = "https://www.xiaohongshu.com/user/profile/5d423fc90000000016034bc6?xsec_token=YBvkMf6BM6shT8zJAPAaDS4TdQNUmu4WskjU5MrT_0mss%3D&xsec_source=app_share&xhsshare=WeixinSession&appuid=5d423fc90000000016034bc6&apptime=1741686168&share_id=5759c5c385644ebf8cf03fea99c2e53e&share_channel=wechat/" },
    { zhihu = "https://zhihu.com/people/nscm/" },
    { xinlangweibo = "https://weibo.com/jincijiayuan/" },
    { email = "mailto:ohulab.org@gmail.com" },
  ]  #文章页作者LOGO下社交媒体图标连接
  email = "ohulab.org@gmail.com"